### ISSUE TITLE
Actualizar widget para calendario

### ISSUE THREAD

**Issue by 007lva** [sramos/LibreTPV#10]
En nuestro intento de actualizar esta app a Rails 4.2, @maxvlc y yo vimos que la gema [calendar_date_select](https://github.com/sramos/LibreTPV/blob/master/Gemfile#L74) es totalmente incompatible. Una salida sencilla seria reemplazarla por el [calendar de jquery ui](https://jqueryui.com/datepicker/), pero teniendo en cuenta que actualmente este proyecto no depende de jquery y que [Rails tambien lo ha quitado como dependencia](https://github.com/rails/rails/issues/25208) me he animado a buscar opciones más modernas y/o interesantes para no tener que introducir una dependencia casi obsoleta.

Es así que he encontrado está posible solución basada en webcomponentes: https://fooloomanzoo.github.io/datetime-picker/components/datetime-picker/. Lo interesante de este webcomponent es que solo se carga si el navegador no soporta nativamente el `<input type=datetime>`(Chrome la soporta muy bien pero Firefox no). De esta manera puede resultar muy ligero para los navegadores que si tengan el widget nativo. Siendo asi, me gustaria empezar a implementarlo en todas las ocurrencias de `<%= fecha ...` ¿Tienes alguna opinión al respecto? ¿Sería bienvenido un pull request con dichos cambios?

**Comment by sramos** [comment]
Me parece buena solución, pero sería mejor modificar el helper "fecha" (en application_helper) para cambiar el calendar_date_select por el webcomponent en lugar de buscarlo en las vistas:

* Es una modificación mucho más simple
* Unificas el comportamiento del elemento en un único punto

**Comment by sramos** [comment]
Mmm...
... acabo de ver un par de vistas donde se usa el helper del plugin en lugar del propio:

```
app/views/albarans/editar.html.erb:    Fecha: <%= date_select('albaran', 'fecha') %>
app/views/factura/_cobrar_albaran.html.erb:    Fecha de Pago<br/><%= date_select('factura', 'fecha') %>
```

Me lo apunto para modificarlas y que usen el helper "fecha" en lugar de meter a capón el selector.

**Comment by 007lva** [comment]
Finalmente el input date nativo será soportado en Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1366188 :)

**Comment by sramos** [comment]
Resuelto
